# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx485tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/skrimpon/Documents/ce432/armv6/armv6.cache/wt [current_project]
set_property parent.project_path /home/skrimpon/Documents/ce432/armv6/armv6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/CLA_4bit.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/CLA_16bit.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/MUX2x1.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/CLA_64bit.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/MCU.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/FA.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/HA.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/CAS.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/non_restoring_division.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/booth_multiplication.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/barrel_shift_right_arithmetical.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/barrel_shift_right_logical.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/barrel_shift_left.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/CLA_32bit.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/barrel_shift_right_cycle.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/register_file.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/hazzard_detection_unit.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/control_unit.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/alu_data_path.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/mul_data_path.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/div_data_path.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/ls_data_path.v
  /home/skrimpon/Documents/ce432/armv6/armv6.srcs/sources_1/new/armv6.v
}
catch { write_hwdef -file armv6.hwdef }
synth_design -top armv6 -part xc7vx485tffg1761-2
write_checkpoint -noxdef armv6.dcp
catch { report_utilization -file armv6_utilization_synth.rpt -pb armv6_utilization_synth.pb }
